In [5]:
import libpysal as ps
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas as pd
import geopandas as gpd
from giddy.ergodic import fmpt

In [2]:
p=np.array([[0.9,0.1],[0.1,0.9]])
p

array([[0.9, 0.1],
       [0.1, 0.9]])

In [6]:
fmpt(p)

array([[ 2., 10.],
       [10.,  2.]])

In [7]:
p=np.array([[0.8,0.2],[0.1,0.9]])
fmpt(p)

array([[ 3. ,  5. ],
       [10. ,  1.5]])

In [4]:
giddy.ergodic.fmpt(p)

array([[ 2., 10.],
       [10.,  2.]])