In [77]:
import mapclassify as mc
import numpy as np
from sklearn import preprocessing
from giddy.markov import Spatial_Markov,LISA_Markov,prais
import libpysal
import numpy.linalg as la
import libpysal as ps

In [83]:

f = libpysal.io.open(libpysal.examples.get_path("usjoin.csv"))
years = list(range(1929, 2010))
pci = np.array([f.by_col[str(y)] for y in years]).transpose()
w = libpysal.io.open(libpysal.examples.get_path("states48.gal")).read()
np.random.seed(10)
lm_random = LISA_Markov(pci, w, permutations=999)
lm_random

In [84]:
for i in range(5):
    r = lm_random.spillover()
    print(i,r['components'][:,12])

0 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]
1 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]
2 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]
3 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]
4 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]


In [88]:
(r['components'][:,12] > 0).sum()

17

In [91]:
(r['spill_over'][:,12]>0).sum()

6

In [94]:
(rn["spill_over"][:,12] > 0).sum()

8

In [79]:

for i in range(5):
    r = lm_random.spillover()
    print(i,r['components'][:,12])

0 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]
1 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]
2 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]
3 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]
4 [0. 0. 0. 1. 0. 2. 2. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 2. 0. 0. 0. 0. 0.
 0. 1. 2. 2. 0. 2. 0. 0. 2. 0. 1. 2. 2. 0. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0.]


In [80]:
r['components'][:,14]

array([0., 1., 0., 1., 0., 2., 2., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       2., 2., 0., 0., 0., 0., 0., 0., 1., 0., 2., 0., 2., 0., 0., 2., 0.,
       1., 2., 2., 0., 0., 0., 0., 0., 2., 0., 1., 2., 0., 0.])

In [81]:
r['spill_over'][:,12]

array([0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.])

In [85]:
for i in range(10):
    rn = lm_random.spillover(neighbors_on=True)
    print(i,rn["components"][:,13])

0 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
1 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
2 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
3 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
4 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
5 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
6 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 

In [87]:
np.unique(rn["components"])

array([0., 1., 2.])

In [82]:
for i in range(10):
    rn = lm_random.spillover(neighbors_on=True)
    print(i,rn["components"][:,13])

0 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
1 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
2 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
3 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
4 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
5 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 1. 2. 2. 0. 1. 0. 1. 1. 2. 2. 1. 2. 0. 1.]
6 [0. 1. 0. 1. 1. 2. 2. 0. 0. 1. 0. 2. 0. 1. 2. 0. 2. 2. 2. 2. 0. 0. 0. 1.
 1. 1. 2. 2. 1. 2. 0. 1. 2. 1. 

In [64]:
rn = lm_random.spillover(neighbors_on=True)

In [66]:
rn['components'][:,12]

array([0., 2., 0., 2., 0., 1., 1., 0., 0., 2., 0., 1., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 2., 0., 2., 1., 1., 0., 1., 0., 0., 1., 0.,
       2., 1., 1., 0., 0., 0., 0., 2., 1., 1., 2., 1., 0., 2.])

In [67]:
rn["spill_over"][:,12]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
lm_random.significant_moves[0,-3:]

array([59, 43, 27])

In [107]:
r = lm_random.spillover()
r

{'components': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 1., 1., ..., 1., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'spill_over': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])}

In [108]:
rn = lm_random.spillover(neighbors_on=True)
rn['components'][:,13]

array([0., 2., 0., 2., 2., 1., 1., 0., 0., 2., 0., 1., 0., 2., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 2., 2., 2., 1., 1., 2., 1., 0., 2., 1., 2.,
       2., 1., 1., 0., 2., 0., 2., 2., 1., 1., 2., 1., 0., 2.])

In [109]:
rn['components'][:,12]

array([0., 2., 0., 2., 0., 1., 1., 0., 0., 2., 0., 1., 0., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 2., 0., 2., 1., 1., 0., 1., 0., 0., 1., 0.,
       2., 1., 1., 0., 0., 0., 0., 2., 1., 1., 2., 1., 0., 2.])

In [95]:
r = lm_random.spillover()
r

{'components': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 1., 1., ..., 1., 1., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'spill_over': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])}

In [11]:
m.p

array([[0.25      , 0.5       , 0.25      ],
       [0.33333333, 0.        , 0.66666667],
       [0.33333333, 0.33333333, 0.33333333]])

In [26]:
f = libpysal.open(libpysal.examples.get_path("usjoin.csv"))
pci = np.array([f.by_col[str(y)] for y in range(1929,2010)])

In [27]:
pci = pci.transpose()
rpci = pci/(pci.mean(axis=0))
rq = mc.Quantiles(rpci.flatten()).yb.reshape(pci.shape)
mq = Markov(rq)
mq.transitions

array([[707.,  58.,   7.,   1.,   0.],
       [ 50., 629.,  80.,   1.,   1.],
       [  4.,  79., 610.,  73.,   2.],
       [  0.,   7.,  72., 650.,  37.],
       [  0.,   0.,   0.,  48., 724.]])

In [5]:
f = ps.open(ps.examples.get_path('usjoin.csv'))
pci = np.array([f.by_col[str(y)] for y in range(1929, 2010)])
pci = pci.transpose()
rpci = pci / (pci.mean(axis=0))
w = ps.open(ps.examples.get_path("states48.gal")).read()
w.transform = 'r'
sm = Spatial_Markov(rpci, w, fixed=True, k=5, m=5)

In [6]:
T = sm.T

In [7]:
P = sm.P

In [8]:
S=sm.S

In [9]:
sm.s

array([0.17957376, 0.21631443, 0.21499942, 0.21134662, 0.17776576])

In [10]:
from scipy import stats
p1 = sm.s
p2 = S[0]
nt = T[0].sum()
o = nt * p2
e = nt * p1
d = np.multiply((o - e), (o - e))
d = d / e
chi2 = d.sum()
pvalue = 1 - stats.chi2.cdf(chi2, sm.k - 1)
pvalue

0.0

In [11]:
sm.shtest

[(461.2096128961479, 0.0, 4),
 (148.14069416285804, 0.0, 4),
 (63.31292613505512, 5.830891325331322e-13, 4),
 (72.27785087142436, 7.549516567451064e-15, 4),
 (232.65920072912445, 0.0, 4)]

In [119]:
chi2

461.2096128961479

In [50]:
chi = np.array([[4.05598541e+01, 6.44644317e-04, 1.60000000e+01],
                         [5.54751974e+01, 2.97033748e-06, 1.60000000e+01],
                         [1.77528996e+01, 3.38563882e-01, 1.60000000e+01],
                         [4.00390961e+01, 7.68422046e-04, 1.60000000e+01],
                         [4.67966803e+01, 7.32512065e-05,
                          1.60000000e+01]])

In [52]:
sm.chi2

[(40.559854126076374, 0.0006446443167027471, 16),
 (55.47519738487663, 2.9703374792022785e-06, 16),
 (17.752899623367387, 0.3385638819692558, 16),
 (40.03909614771082, 0.0007684220464208025, 16),
 (46.796680348736864, 7.325120646395344e-05, 16)]

In [47]:
m.steady_state

array([0.20774716, 0.18725774, 0.20740537, 0.18821787, 0.20937187])

In [43]:
expected = np.array([[729., 71., 1., 0., 0.],
                             [72., 567., 80., 3., 0.],
                             [0., 81., 631., 86., 2.],
                             [0., 3., 86., 573., 56.],
                             [0., 0., 1., 57., 741.]])

In [44]:
np.testing.assert_array_equal(m.transitions, expected)

In [46]:
expected.getA()

AttributeError: 'numpy.ndarray' object has no attribute 'getA'

In [29]:
rpci = pci/(pci.mean(axis=0))
w = libpysal.open(libpysal.examples.get_path("states48.gal")).read()
w.transform = 'r'

In [34]:
w = libpysal.open(libpysal.examples.get_path("states48.gal")).read()

In [53]:
lm = LISA_Markov(pci,w)

In [54]:
lm.classes

array([1, 2, 3, 4])

In [55]:
lm.steady_state

array([0.28561505, 0.14190226, 0.40493672, 0.16754598])

In [60]:
f = ps.open(ps.examples.get_path('usjoin.csv'))
pci = np.array([f.by_col[str(y)] for y in range(1929, 2010)])
q5 = np.array([mc.Quantiles(y).yb for y in pci]).transpose()
m = Markov(q5)

In [62]:
m.p

array([[0.91011236, 0.0886392 , 0.00124844, 0.        , 0.        ],
       [0.09972299, 0.78531856, 0.11080332, 0.00415512, 0.        ],
       [0.        , 0.10125   , 0.78875   , 0.1075    , 0.0025    ],
       [0.        , 0.00417827, 0.11977716, 0.79805014, 0.07799443],
       [0.        , 0.        , 0.00125156, 0.07133917, 0.92740926]])

In [61]:
prais(m.p)

0.0898876404494382

In [71]:
pmat = np.matrix(m.p)
pmat.sum(axis=1)

matrix([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [78]:
w.transform = 'b'

In [81]:
f = libpysal.open(libpysal.examples.get_path("usjoin.csv"))
pci = np.array([f.by_col[str(y)] for y in range(1929,2010)])
pci = pci.transpose()
rpci = pci/(pci.mean(axis=0))
w = libpysal.open(libpysal.examples.get_path("states48.gal")).read()
w.transform = 'r'
cc = np.array([0.8, 0.9, 1, 1.2])
sm = Spatial_Markov(rpci, w, cutoffs=cc, lag_cutoffs=cc, variable_name='rpci')
sm.P

array([[[0.96703297, 0.03296703, 0.        , 0.        , 0.        ],
        [0.10638298, 0.68085106, 0.21276596, 0.        , 0.        ],
        [0.        , 0.14285714, 0.7755102 , 0.08163265, 0.        ],
        [0.        , 0.        , 0.5       , 0.5       , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ]],

       [[0.88636364, 0.10606061, 0.00757576, 0.        , 0.        ],
        [0.04402516, 0.89308176, 0.06289308, 0.        , 0.        ],
        [0.        , 0.05882353, 0.8627451 , 0.07843137, 0.        ],
        [0.        , 0.        , 0.13846154, 0.86153846, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 1.        ]],

       [[0.78082192, 0.17808219, 0.02739726, 0.01369863, 0.        ],
        [0.03488372, 0.90406977, 0.05813953, 0.00290698, 0.        ],
        [0.        , 0.05919003, 0.84735202, 0.09034268, 0.00311526],
        [0.        , 0.        , 0.05811623, 0.92985972, 0.01202405],
        [0.     

In [83]:
y = mc.Quantiles(rpci.flatten(), k=5).yb.reshape(rpci.shape)
y

array([[0, 0, 0, ..., 1, 1, 1],
       [2, 2, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [3, 3, 2, ..., 2, 2, 2],
       [3, 3, 3, ..., 4, 4, 3]])

In [90]:
for p in sm.P:
    print(p)

[[0.94787645 0.04440154 0.00772201 0.         0.        ]
 [0.08333333 0.81060606 0.10606061 0.         0.        ]
 [0.         0.12765957 0.79787234 0.07446809 0.        ]
 [0.         0.02777778 0.22222222 0.66666667 0.08333333]
 [0.         0.         0.         0.33333333 0.66666667]]
[[0.888      0.096      0.016      0.         0.        ]
 [0.06049822 0.84341637 0.09608541 0.         0.        ]
 [0.00666667 0.10666667 0.81333333 0.07333333 0.        ]
 [0.         0.         0.08527132 0.86821705 0.04651163]
 [0.         0.         0.         0.10204082 0.89795918]]
[[0.65217391 0.32608696 0.02173913 0.         0.        ]
 [0.07446809 0.80851064 0.11170213 0.         0.00531915]
 [0.01071429 0.1        0.76428571 0.11785714 0.00714286]
 [0.         0.00552486 0.09392265 0.86187845 0.03867403]
 [0.         0.         0.         0.13157895 0.86842105]]
[[0.91935484 0.06451613 0.         0.01612903 0.        ]
 [0.06796117 0.90291262 0.02912621 0.         0.        ]
 [0.       

In [88]:
w.transform = 'b'
np.random.seed(5)
sm = Spatial_Markov(y, w, discrete=True, variable_name='discretized rpci')
sm.P

array([[[0.94787645, 0.04440154, 0.00772201, 0.        , 0.        ],
        [0.08333333, 0.81060606, 0.10606061, 0.        , 0.        ],
        [0.        , 0.12765957, 0.79787234, 0.07446809, 0.        ],
        [0.        , 0.02777778, 0.22222222, 0.66666667, 0.08333333],
        [0.        , 0.        , 0.        , 0.33333333, 0.66666667]],

       [[0.888     , 0.096     , 0.016     , 0.        , 0.        ],
        [0.06049822, 0.84341637, 0.09608541, 0.        , 0.        ],
        [0.00666667, 0.10666667, 0.81333333, 0.07333333, 0.        ],
        [0.        , 0.        , 0.08527132, 0.86821705, 0.04651163],
        [0.        , 0.        , 0.        , 0.10204082, 0.89795918]],

       [[0.65217391, 0.32608696, 0.02173913, 0.        , 0.        ],
        [0.07446809, 0.80851064, 0.11170213, 0.        , 0.00531915],
        [0.01071429, 0.1       , 0.76428571, 0.11785714, 0.00714286],
        [0.        , 0.00552486, 0.09392265, 0.86187845, 0.03867403],
        [0.     

In [89]:
w.transform = 'r'
np.random.seed(5)
sm = Spatial_Markov(y, w, discrete=True, variable_name='discretized rpci')
sm.P

array([[[0.94787645, 0.04440154, 0.00772201, 0.        , 0.        ],
        [0.08333333, 0.81060606, 0.10606061, 0.        , 0.        ],
        [0.        , 0.12765957, 0.79787234, 0.07446809, 0.        ],
        [0.        , 0.02777778, 0.22222222, 0.66666667, 0.08333333],
        [0.        , 0.        , 0.        , 0.33333333, 0.66666667]],

       [[0.888     , 0.096     , 0.016     , 0.        , 0.        ],
        [0.06049822, 0.84341637, 0.09608541, 0.        , 0.        ],
        [0.00666667, 0.10666667, 0.81333333, 0.07333333, 0.        ],
        [0.        , 0.        , 0.08527132, 0.86821705, 0.04651163],
        [0.        , 0.        , 0.        , 0.10204082, 0.89795918]],

       [[0.65217391, 0.32608696, 0.02173913, 0.        , 0.        ],
        [0.07446809, 0.80851064, 0.11170213, 0.        , 0.00531915],
        [0.01071429, 0.1       , 0.76428571, 0.11785714, 0.00714286],
        [0.        , 0.00552486, 0.09392265, 0.86187845, 0.03867403],
        [0.     

In [74]:
1- np.diag(pmat)

array([0.08988764, 0.21468144, 0.21125   , 0.20194986, 0.07259074])

In [73]:
pmat.sum(axis=1) - np.diag(pmat)

matrix([[0.08988764, 0.21468144, 0.21125   , 0.20194986, 0.07259074],
        [0.08988764, 0.21468144, 0.21125   , 0.20194986, 0.07259074],
        [0.08988764, 0.21468144, 0.21125   , 0.20194986, 0.07259074],
        [0.08988764, 0.21468144, 0.21125   , 0.20194986, 0.07259074],
        [0.08988764, 0.21468144, 0.21125   , 0.20194986, 0.07259074]])

In [70]:
pmat = m.p
pmat.sum(axis=1)

array([1., 1., 1., 1., 1.])

In [66]:
np.diag(pmat)

array([0.91011236, 0.78531856, 0.78875   , 0.79805014, 0.92740926])

In [39]:
lm.p

array([[0.92985458, 0.03763901, 0.00342173, 0.02908469],
       [0.07481752, 0.85766423, 0.06569343, 0.00182482],
       [0.00333333, 0.02266667, 0.948     , 0.026     ],
       [0.04815409, 0.00160514, 0.06420546, 0.88603531]])

In [30]:
sm = Spatial_Markov(rpci, w, fixed=True, k=5, m=5, variable_name='rpci')

In [31]:
sm.cutoffs

array([0.83999133, 0.94707545, 1.03242697, 1.14911154])

In [32]:
sm.lag_cutoffs

array([0.88973386, 0.95891917, 1.01469758, 1.1183566 ])

In [28]:
mq.steady_state

array([0.17957376, 0.21631443, 0.21499942, 0.21134662, 0.17776576])

In [2]:
from giddy.api import steady_state,fmpt,var_fmpt
p=np.array([[.5, .25, .25],[.5,0,.5],[.25,.25,.5]])
steady_state(p)

array([0.4, 0.2, 0.4])

In [3]:
var_fmpt(p)

array([[ 5.58333333, 12.        ,  6.88888889],
       [ 6.22222222, 12.        ,  6.22222222],
       [ 6.88888889, 12.        ,  5.58333333]])

In [7]:
np.array([0.4, 0.2, 0.4])

array([0.4, 0.2, 0.4])

In [10]:
P=p
P = np.matrix(P)
A = np.zeros_like(P)
ss = steady_state(P).reshape(3,1)
k = ss.shape[0]
for i in range(k):
    A[:, i] = ss
A = A.transpose()
I = np.identity(k)
Z = la.inv(I - P + A)
E = np.ones_like(Z)
A_diag = np.diag(A)
A_diag = A_diag + (A_diag==0)
D = np.diag(1. / A_diag)
Zdg = np.diag(np.diag(Z))
M = (I - Z + E * Zdg) * D
M

matrix([[2.5       , 4.        , 3.33333333],
        [2.66666667, 5.        , 2.66666667],
        [3.33333333, 4.        , 2.5       ]])

In [4]:
fmpt(p)

ValueError: could not broadcast input array from shape (3,1) into shape (3)

In [66]:
p

matrix([[0.5 , 0.25, 0.25],
        [0.5 , 0.  , 0.5 ],
        [0.25, 0.25, 0.5 ]])

In [67]:
P=np.matrix(p)
A = P ** 1000
n, k = A.shape
I = np.identity(k)
Z = la.inv(I - P + A)
E = np.ones_like(Z)
D = np.diag(1. / np.diag(A))
Zdg = np.diag(np.diag(Z))
M = (I - Z + E * Zdg) * D
ZM = Z * M
ZMdg = np.diag(np.diag(ZM))
W = M * (2 * Zdg * D - I) + 2 * (ZM - E * ZMdg)
W - np.multiply(M, M)

matrix([[ 5.58333333, 12.        ,  6.88888889],
        [ 6.22222222, 12.        ,  6.22222222],
        [ 6.88888889, 12.        ,  5.58333333]])

In [65]:
W

matrix([[11.83333333, 28.        , 18.        ],
        [13.33333333, 37.        , 13.33333333],
        [18.        , 28.        , 11.83333333]])

In [60]:
P ** 1000

matrix([[0.4, 0.2, 0.4],
        [0.4, 0.2, 0.4],
        [0.4, 0.2, 0.4]])

In [61]:
p

matrix([[0.5 , 0.25, 0.25],
        [0.5 , 0.  , 0.5 ],
        [0.25, 0.25, 0.5 ]])

In [59]:
A

matrix([[0.4, 0.2, 0.4],
        [0.4, 0.2, 0.4],
        [0.4, 0.2, 0.4]])

In [52]:
W

matrix([[11.83333333, 28.        , 18.        ],
        [13.33333333, 37.        , 13.33333333],
        [18.        , 28.        , 11.83333333]])

In [26]:
fm=fmpt(p)
fm

array([[ 2.5, -0. ,  0. ],
       [-0. ,  5. , -0. ],
       [ 0. , -0. ,  2.5]])

In [28]:
P = p
A = np.zeros_like(P)
ss = steady_state(P)
k = ss.shape[0]
for i in range(k):
    A[:, i] = ss
A = A.transpose()
I = np.identity(k)
Z = la.inv(I - P + A)
E = np.ones_like(Z)
A_diag = np.diag(A)
A_diag = A_diag + (A_diag==0)
D = np.diag(1. / A_diag)
Zdg = np.diag(np.diag(Z))
M = (I - Z + E * Zdg) * D
M

array([[ 2.5, -0. ,  0. ],
       [-0. ,  5. , -0. ],
       [ 0. , -0. ,  2.5]])

In [31]:
np.matrix(steady_state(p)).reshape(3,1)

matrix([[0.4],
        [0.2],
        [0.4]])

In [34]:
A

matrix([[0.4, 0.2, 0.4],
        [0.4, 0.2, 0.4],
        [0.4, 0.2, 0.4]])

In [44]:
ss = np.matrix(steady_state(p)).reshape(3,1)
k = ss.shape[0]
for i in range(k):
    A[:, i] = ss
A = A.transpose()
I = np.identity(k)
Z = np.array(la.inv(I - P + A))
E = np.ones_like(Z)
A_diag = np.diag(A)
A_diag = A_diag + (A_diag==0)
D = np.diag(1. / A_diag)
Zdg = np.diag(np.diag(Z))
M = (I - Z + E * Zdg) * D
M

array([[ 2.5, -0. ,  0. ],
       [-0. ,  5. , -0. ],
       [ 0. , -0. ,  2.5]])

In [43]:
Z

matrix([[ 1.14666667,  0.04      , -0.18666667],
        [ 0.08      ,  0.84      ,  0.08      ],
        [-0.18666667,  0.04      ,  1.14666667]])

In [42]:
np.ones_like(Z)

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
A = np.zeros_like(P)
ss = steady_state(P).reshape(3,1)
k = ss.shape[0]
for i in range(k):
    A[:, i] = ss
A = A.transpose()
I = np.identity(k)
Z = la.inv(I - P + A)
E = np.ones_like(Z)
A_diag = np.diag(A)
A_diag = A_diag + (A_diag==0)
D = np.diag(1. / A_diag)
Zdg = np.diag(np.diag(Z))
M = (I - Z + E * Zdg) * D
M

matrix([[2.5       , 4.        , 3.33333333],
        [2.66666667, 5.        , 2.66666667],
        [3.33333333, 4.        , 2.5       ]])

In [39]:
Zdg

array([[1.14666667, 0.        , 0.        ],
       [0.        , 0.84      , 0.        ],
       [0.        , 0.        , 1.14666667]])

In [41]:
E

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
ss

array([0.4, 0.2, 0.4])

In [13]:
ss = steady_state(p)
k = ss.shape[0]

In [14]:
k

3

In [15]:
A = np.zeros_like(p)
for i in range(k):
    A[:, i] = ss

In [16]:
A

array([[0.4, 0.4, 0.4],
       [0.2, 0.2, 0.2],
       [0.4, 0.4, 0.4]])

In [22]:
import numpy.linalg as la
P = p
A = A.transpose()
I = np.identity(k)
Z = la.inv(I - P + A)
E = np.ones_like(Z)
A_diag = np.diag(A)
A_diag = A_diag + (A_diag==0)
D = np.diag(1. / A_diag)
Zdg = np.diag(np.diag(Z))
M = (I - Z + E * Zdg) * D

In [23]:
M

array([[ 2.5, -0. ,  0. ],
       [-0. ,  5. , -0. ],
       [ 0. , -0. ,  2.5]])

In [2]:
f = libpysal.open(libpysal.examples.get_path("usjoin.csv"))
pci = np.array([f.by_col[str(y)] for y in range(1929,2010)])
pci = pci.transpose()
rpci = pci/(pci.mean(axis=0))
w = libpysal.open(libpysal.examples.get_path("states48.gal")).read()
w.transform = 'r'
sm = Spatial_Markov(rpci, w, fixed=True, k=5, m=5, variable_name='rpci')
sm.summary()

--------------------------------------------------------------
                  Spatial Markov Test: rpci                   
--------------------------------------------------------------
Number of classes: 5
Number of transitions: 3840
Number of regimes: 5
Regime names: LAG0, LAG1, LAG2, LAG3, LAG4
--------------------------------------------------------------
   Test                   LR                Chi-2
  Stat.              170.659              200.624
    DOF                   60                   60
p-value                0.000                0.000
--------------------------------------------------------------
P(H0)           C0         C1         C2         C3         C4
     C0      0.915      0.075      0.009      0.001      0.000
     C1      0.066      0.827      0.105      0.001      0.001
     C2      0.005      0.103      0.794      0.095      0.003
     C3      0.000      0.009      0.094      0.849      0.048
     C4      0.000      0.000      0.000      0.062      

In [3]:
sm.cutoffs

array([0.83999133, 0.94707545, 1.03242697, 1.14911154])

In [4]:
sm.lag_cutoffs

array([0.88973386, 0.95891917, 1.01469758, 1.1183566 ])

In [5]:
sm.class_ids

array([[0, 0, 0, ..., 1, 1, 1],
       [2, 2, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [3, 3, 2, ..., 2, 2, 2],
       [3, 3, 3, ..., 4, 4, 3]])

In [5]:
print(sm.p)

[[0.91461837 0.07503234 0.00905563 0.00129366 0.        ]
 [0.06570302 0.82654402 0.10512484 0.00131406 0.00131406]
 [0.00520833 0.10286458 0.79427083 0.09505208 0.00260417]
 [0.         0.00913838 0.09399478 0.84856397 0.04830287]
 [0.         0.         0.         0.06217617 0.93782383]]


In [4]:
import libpysal as ps
f = ps.open(ps.examples.get_path('usjoin.csv'))
pci = np.array([f.by_col[str(y)] for y in range(1929, 2010)])
pci = pci.transpose()
rpci = pci / (pci.mean(axis=0))

In [6]:
cc = np.array([0.8, 0.9, 1, 1.2])
sm = Spatial_Markov(rpci, w,cutoffs=cc, lag_cutoffs=cc)
sm.P

array([[[0.96703297, 0.03296703, 0.        , 0.        , 0.        ],
        [0.10638298, 0.68085106, 0.21276596, 0.        , 0.        ],
        [0.        , 0.14285714, 0.7755102 , 0.08163265, 0.        ],
        [0.        , 0.        , 0.5       , 0.5       , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ]],

       [[0.88636364, 0.10606061, 0.00757576, 0.        , 0.        ],
        [0.04402516, 0.89308176, 0.06289308, 0.        , 0.        ],
        [0.        , 0.05882353, 0.8627451 , 0.07843137, 0.        ],
        [0.        , 0.        , 0.13846154, 0.86153846, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 1.        ]],

       [[0.78082192, 0.17808219, 0.02739726, 0.01369863, 0.        ],
        [0.03488372, 0.90406977, 0.05813953, 0.00290698, 0.        ],
        [0.        , 0.05919003, 0.84735202, 0.09034268, 0.00311526],
        [0.        , 0.        , 0.05811623, 0.92985972, 0.01202405],
        [0.     

In [8]:
sm.S

array([[ 0.54148249,  0.16780007,  0.24991499,  0.04080245, -0.        ],
       [ 0.12336693,  0.31843086,  0.35634884,  0.20185337, -0.        ],
       [ 0.03607655,  0.22667277,  0.25883041,  0.43607249,  0.04234777],
       [ 0.05016931,  0.11306259,  0.24790153,  0.39272546,  0.19614112],
       [-0.        ,  0.01394504,  0.20625861,  0.31357586,  0.46622049]])

In [10]:
sm.p

matrix([[9.07547170e-01, 8.30188679e-02, 5.66037736e-03, 3.77358491e-03,
         0.00000000e+00],
        [4.86725664e-02, 8.64306785e-01, 8.25958702e-02, 4.42477876e-03,
         0.00000000e+00],
        [1.19047619e-03, 6.54761905e-02, 8.36904762e-01, 9.40476190e-02,
         2.38095238e-03],
        [0.00000000e+00, 8.23045267e-04, 7.24279835e-02, 9.02057613e-01,
         2.46913580e-02],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.10571924e-02,
         9.28942808e-01]])

In [11]:
sm.transitions

array([[4.810e+02, 4.400e+01, 3.000e+00, 2.000e+00, 0.000e+00],
       [3.300e+01, 5.860e+02, 5.600e+01, 3.000e+00, 0.000e+00],
       [1.000e+00, 5.500e+01, 7.030e+02, 7.900e+01, 2.000e+00],
       [0.000e+00, 1.000e+00, 8.800e+01, 1.096e+03, 3.000e+01],
       [0.000e+00, 0.000e+00, 0.000e+00, 4.100e+01, 5.360e+02]])

In [12]:
transitions = sm.transitions
row_sum = transitions.sum(axis=1)

In [13]:
np.dot(np.diag(1 / (row_sum + (row_sum == 0))), transitions)

array([[9.07547170e-01, 8.30188679e-02, 5.66037736e-03, 3.77358491e-03,
        0.00000000e+00],
       [4.86725664e-02, 8.64306785e-01, 8.25958702e-02, 4.42477876e-03,
        0.00000000e+00],
       [1.19047619e-03, 6.54761905e-02, 8.36904762e-01, 9.40476190e-02,
        2.38095238e-03],
       [0.00000000e+00, 8.23045267e-04, 7.24279835e-02, 9.02057613e-01,
        2.46913580e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.10571924e-02,
        9.28942808e-01]])

In [36]:
import numpy.linalg as la
v, d = la.eig(np.transpose(sm.P[0]))

In [37]:
d = np.array(d)

In [38]:
mv = max(v)

In [39]:
v

array([1.        , 0.94265065, 0.61293802, 0.36780557, 0.        ])

In [40]:
i = v.tolist().index(mv)

In [41]:
i

0

In [45]:
abs(d[:, i]) 

array([0.87213173, 0.270265  , 0.40252234, 0.06571793, 0.        ])

In [43]:
sum(d[:, i])

-1.610636995673892

In [44]:
d[:, i] / sum(d[:, i])

array([ 0.54148249,  0.16780007,  0.24991499,  0.04080245, -0.        ])

In [7]:
sm.cutoffs

array([0.83999133, 0.94707545, 1.03242697, 1.14911154])

In [8]:
sm.lag_cutoffs

array([0.91440247, 0.98583079, 1.08698351])

In [34]:
row = d[:, i]

In [35]:
row

array([0.20335103, 0.37383522, 0.50808137, 0.70190225, 0.26092555])

In [9]:
for p in sm.P:
     print(p)

[[0.95708955 0.03544776 0.00746269 0.         0.        ]
 [0.05825243 0.83980583 0.10194175 0.         0.        ]
 [0.         0.1294964  0.76258993 0.10791367 0.        ]
 [0.         0.01538462 0.18461538 0.72307692 0.07692308]
 [0.         0.         0.         0.14285714 0.85714286]]
[[0.7421875  0.234375   0.0234375  0.         0.        ]
 [0.08550186 0.85130112 0.06319703 0.         0.        ]
 [0.00865801 0.06926407 0.86147186 0.05627706 0.004329  ]
 [0.         0.         0.05363985 0.92337165 0.02298851]
 [0.         0.         0.         0.13432836 0.86567164]]
[[0.95145631 0.04854369 0.         0.         0.        ]
 [0.06       0.79       0.145      0.         0.005     ]
 [0.00358423 0.10394265 0.7921147  0.09677419 0.00358423]
 [0.         0.01630435 0.13586957 0.75543478 0.0923913 ]
 [0.         0.         0.         0.10204082 0.89795918]]
[[0.16666667 0.66666667 0.         0.16666667 0.        ]
 [0.03488372 0.80232558 0.15116279 0.01162791 0.        ]
 [0.0084033

In [10]:
"%.3f"%sm.LR

'172.105'

In [11]:
"%.3f"%sm.Q

'321.128'

In [12]:
"%.3f"%sm.LR_p_value

'0.000'

In [13]:
sm.dof_hom

45

In [14]:
sm.cutoffs

array([0.83999133, 0.94707545, 1.03242697, 1.14911154])

In [3]:
cc = np.array([0.8, 0.9, 1, 1.2])

In [4]:
sm = Spatial_Markov(rpci, w, cutoffs=cc, lag_cutoffs=cc, variable_name='rpci')
sm.summary()

--------------------------------------------------------------
                  Spatial Markov Test: rpci                   
--------------------------------------------------------------
Number of classes: 5
Number of transitions: 3840
Number of regimes: 5
Regime names: LAG0, LAG1, LAG2, LAG3, LAG4
--------------------------------------------------------------
   Test                   LR                Chi-2
  Stat.              104.187              117.419
    DOF                   49                   49
p-value                0.000                0.000
--------------------------------------------------------------
P(H0)           C0         C1         C2         C3         C4
     C0      0.908      0.083      0.006      0.004      0.000
     C1      0.049      0.864      0.083      0.004      0.000
     C2      0.001      0.065      0.837      0.094      0.002
     C3      0.000      0.001      0.072      0.902      0.025
     C4      0.000      0.000      0.000      0.071      

In [5]:
sm.cutoffs

array([0.8, 0.9, 1. , 1.2])

In [6]:
sm.lag_cutoffs

array([0.8, 0.9, 1. , 1.2])

In [7]:
sm.k

5

In [8]:
sm.m

5

In [6]:
for p in sm.P:
    print(p)

[[0.96703297 0.03296703 0.         0.         0.        ]
 [0.10638298 0.68085106 0.21276596 0.         0.        ]
 [0.         0.14285714 0.7755102  0.08163265 0.        ]
 [0.         0.         0.5        0.5        0.        ]
 [0.         0.         0.         0.         0.        ]]
[[0.88636364 0.10606061 0.00757576 0.         0.        ]
 [0.04402516 0.89308176 0.06289308 0.         0.        ]
 [0.         0.05882353 0.8627451  0.07843137 0.        ]
 [0.         0.         0.13846154 0.86153846 0.        ]
 [0.         0.         0.         0.         1.        ]]
[[0.78082192 0.17808219 0.02739726 0.01369863 0.        ]
 [0.03488372 0.90406977 0.05813953 0.00290698 0.        ]
 [0.         0.05919003 0.84735202 0.09034268 0.00311526]
 [0.         0.         0.05811623 0.92985972 0.01202405]
 [0.         0.         0.         0.14285714 0.85714286]]
[[0.82692308 0.15384615 0.         0.01923077 0.        ]
 [0.0703125  0.7890625  0.125      0.015625   0.        ]
 [0.0029585

In [ ]:
sm = Spatial_Markov(rpci, w, fixed=False, k=5, m=4, variable_name='rpci')
sm.summary()

In [6]:
y = mc.Quantiles(rpci.flatten(), k=5).yb.reshape(rpci.shape)

In [7]:

sm = Spatial_Markov(y, w, discrete=True, variable_name='discretized rpci')

In [8]:
sm.classes

array([0, 1, 2, 3, 4])

In [9]:
rpci = pci / (pci.mean(axis=0))

In [11]:
discretized = (rpci * 100).astype(int) % 4
discretized

array([[0, 1, 1, ..., 2, 2, 2],
       [1, 3, 1, ..., 2, 3, 2],
       [2, 1, 3, ..., 3, 3, 0],
       ...,
       [2, 3, 2, ..., 0, 2, 1],
       [1, 0, 2, ..., 0, 0, 3],
       [1, 3, 0, ..., 1, 2, 2]])

In [17]:
import libpysal as ps
w = ps.weights.Contiguity.Queen.from_shapefile(ps.examples.get_path('us48.shp'))
np.random.seed(24788)

In [18]:
sm = Spatial_Markov(discretized, w, discrete=True)

In [19]:
sm.classes

array([0, 1, 2, 3])

In [21]:
sm.class_ids

array([[0, 1, 1, ..., 2, 2, 2],
       [1, 3, 1, ..., 2, 3, 2],
       [2, 1, 3, ..., 3, 3, 0],
       ...,
       [2, 3, 2, ..., 0, 2, 1],
       [1, 0, 2, ..., 0, 0, 3],
       [1, 3, 0, ..., 1, 2, 2]])

In [22]:
sm.T

array([[[ 82.,  80.,  72.,  86.],
        [ 85., 100.,  88.,  78.],
        [ 74.,  90., 116.,  75.],
        [ 89.,  65.,  78.,  86.]],

       [[ 73.,  59.,  45.,  67.],
        [ 64.,  62.,  62.,  54.],
        [ 63.,  60.,  71.,  73.],
        [ 51.,  55.,  86.,  74.]],

       [[ 68.,  53.,  46.,  61.],
        [ 44.,  52.,  60.,  37.],
        [ 41.,  45.,  79.,  50.],
        [ 43.,  55.,  57.,  70.]],

       [[ 46.,  41.,  34.,  28.],
        [ 40.,  45.,  39.,  35.],
        [ 38.,  51.,  43.,  40.],
        [ 37.,  25.,  41.,  33.]]])

In [31]:
ps.lag_categorical?

In [30]:
import libpysal.api as ps
ps.lag_categorical(w, sm.classes)

array([[0, 0, 0, ..., 1, 1, 1],
       [4, 4, 0, ..., 3, 3, 3],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [4, 4, 4, ..., 0, 0, 4],
       [4, 4, 4, ..., 3, 3, 3],
       [2, 1, 0, ..., 1, 1, 2]])

In [26]:
for p in sm.P:
    print(p)

[[0.94412331 0.04624277 0.00963391 0.         0.        ]
 [0.06504065 0.82113821 0.11382114 0.         0.        ]
 [0.         0.15151515 0.77777778 0.07070707 0.        ]
 [0.         0.02777778 0.25       0.66666667 0.05555556]
 [0.         0.         0.         0.15384615 0.84615385]]
[[0.896      0.096      0.008      0.         0.        ]
 [0.06810036 0.83870968 0.09318996 0.         0.        ]
 [0.00636943 0.0955414  0.82802548 0.07006369 0.        ]
 [0.         0.         0.0729927  0.87591241 0.05109489]
 [0.         0.         0.         0.125      0.875     ]]
[[0.67346939 0.30612245 0.02040816 0.         0.        ]
 [0.07179487 0.81538462 0.10769231 0.         0.00512821]
 [0.01071429 0.09642857 0.77142857 0.11428571 0.00714286]
 [0.         0.00558659 0.09497207 0.8547486  0.04469274]
 [0.         0.         0.         0.125      0.875     ]]
[[0.9137931  0.06896552 0.         0.01724138 0.        ]
 [0.07407407 0.88888889 0.03703704 0.         0.        ]
 [0.       

In [22]:
sm = Spatial_Markov(y, w, discrete=True, variable_name='discretized rpci')

In [25]:
sm.k

5

In [26]:
sm.m

5

In [28]:
for p in sm.P:
    print(p)

[[0.94401544 0.04826255 0.00772201 0.         0.        ]
 [0.06451613 0.83064516 0.10483871 0.         0.        ]
 [0.         0.09677419 0.8172043  0.08602151 0.        ]
 [0.         0.02702703 0.24324324 0.64864865 0.08108108]
 [0.         0.         0.         0.25       0.75      ]]
[[0.8976378  0.09448819 0.00787402 0.         0.        ]
 [0.06315789 0.83157895 0.10526316 0.         0.        ]
 [0.00653595 0.10457516 0.81045752 0.07843137 0.        ]
 [0.         0.         0.0729927  0.89051095 0.03649635]
 [0.         0.         0.         0.12       0.88      ]]
[[0.68888889 0.28888889 0.02222222 0.         0.        ]
 [0.08333333 0.8125     0.09895833 0.         0.00520833]
 [0.01048951 0.11188811 0.75874126 0.11188811 0.00699301]
 [0.         0.00558659 0.08938547 0.86592179 0.03910615]
 [0.         0.         0.         0.14285714 0.85714286]]
[[0.87301587 0.0952381  0.01587302 0.01587302 0.        ]
 [0.05769231 0.91346154 0.02884615 0.         0.        ]
 [0.       

In [15]:
y = mc.Quantiles(rpci.flatten(), k=5).yb
y_pool = y.flatten()
le = preprocessing.LabelEncoder()
le.fit(y_pool)
y_pool_int = le.transform(y_pool)
yint = y_pool_int.reshape(rpci.shape)
yint

array([[0, 0, 0, ..., 1, 1, 1],
       [2, 2, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [3, 3, 2, ..., 2, 2, 2],
       [3, 3, 3, ..., 4, 4, 3]])

In [25]:
len(np.unique(y))

4

In [22]:
y_pool = y.flatten()
le = preprocessing.LabelEncoder()
le.fit(y_pool)
y_pool_int = le.transform(y_pool)
yint = y_pool_int.reshape(y.shape)

In [27]:
len(le.classes_)

4

In [23]:
yint

array([[0, 1, 3, 3, 0, 2],
       [0, 1, 3, 3, 0, 0]])

In [4]:
mc.api

AttributeError: module 'mapclassify' has no attribute 'api'